version: '3'

services:
  api:
     image: weissale1/weatherstation:0.0.5
     ports:
       - "8080:8080"
     depends_on:
       - db
     environment:
       TZ: Europe/Berlin
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
     networks:
       - weather_net

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      TZ: Europe/Berlin
      POSTGRES_PASSWORD: example
    volumes:
      - weather_db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - weather_net

  sensors:
    image: weissale1/weathersensors:0.0.5
    privileged: true
    ports:
      - "5000:5000"
    environment:
      TZ: Europe/Berlin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - weather_net

volumes:
  weather_db:

networks:
  weather_net:
    driver: bridge