version: '3'

services:
  api:
     image: weissale1/weatherstation:0.0.2
     ports:
       - "5000:5000"
     depends_on:
       - db
     networks:
       - weather_net

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - weather_db:/var/lib/postgresql/data
    networks:
      - weather_net

volumes:
  weather_db:

networks:
  weather_net:
    driver: bridge